### ISSUE TITLE
Proposal Notes W7D5

### ISSUE THREAD

**Issue by BCrawfordScott** [Numie/FoodDotCom#1]
-Let's scale back the depth of our menus, and focus more on core MVPs.  Lets only go as deep as menu items, no options.  We may also want to leave menu sections for now, and implement it after if we have time.  We can talk more about this in person, but this really becomes a question of 'need to haves' vs 'want to haves' with your MVPs.

-We may want to add a route to past orders as part of the orders MVP.

**Comment by Numie** [comment]
Ok, I’m down to discuss it any time. If it’s at all possible, I really want to try to implement the options. They’re really critical!

On Mar 2, 2018, at 9:23 AM, Brian Crawford Scott <notifications@github.com<mailto:notifications@github.com>> wrote:


-Let's scale back the depth of our menus, and focus more on core MVPs. Lets only go as deep as menu items, no options. We may also want to leave menu sections for now, and implement it after if we have time. We can talk more about this in person, but this really becomes a question of 'need to haves' vs 'want to haves' with your MVPs.

-We may want to add a route to past orders as part of the orders MVP.

**Comment by Numie** [comment]
Schema and Sample State updated to account for menu items only.
