### ISSUE TITLE
PA Review: Restaurants

### ISSUE THREAD

**Issue by Numie** [Numie/FoodDotCom#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Restaurant Search Bar
- [x] Restaurant Search Functionality
- [x] Restaurant Index
- [x] Restaurant Show
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by BCrawfordScott** [comment]
Excellent work.  Looks great so far.   When you're ready, remember to make your seeds unique for each restaurant.  It'll make everything seem more polished.
